name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - 'proxy-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-sm-network:
    if: startsWith(github.ref_name, 'v')
    permissions:
      id-token: write
    uses: sm-packages/.github/.github/workflows/publish-pub-dev.yml@v2
    with:
      working-directory: sm_network

  publish-sm-network-proxy:
    if: startsWith(github.ref_name, 'proxy-v')
    permissions:
      id-token: write
    uses: sm-packages/.github/.github/workflows/publish-pub-dev.yml@v2
    with:
      working-directory: sm_network_proxy
